"""
Django settings for PauliCode project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*e7y)ze6r)abbf6l=kq6@&np+n_ryrws0q!q-=4$l&(3^gb2h4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'User',
    'channels',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'PauliCode.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'PauliCode.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'djangoPauliCode',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}


# ============================================
# CUSTOM AUTHENTICATION CONFIGURATION
# ============================================
AUTH_USER_MODEL = 'User.User'
# Authentication Backends - Use custom backend for school_id login
AUTHENTICATION_BACKENDS = [
    'User.auth_backend.SchoolIDBackend',  # Primary: Custom school_id authentication
    'User.auth_backend.SessionAuthBackend',  # Secondary: Session-based authentication
    'django.contrib.auth.backends.ModelBackend',  # Fallback: Default Django auth
]

# Login/Logout URLs
LOGIN_URL = 'index'  # Redirect here when @login_required fails
LOGIN_REDIRECT_URL = 'dashboard'  # Default redirect after login (can be overridden in views)
LOGOUT_REDIRECT_URL = 'index'  # Redirect here after logout

# Session Configuration
SESSION_COOKIE_AGE = 86400  # 24 hours (in seconds)
SESSION_SAVE_EVERY_REQUEST = True  # Update session on every request
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Keep session even after browser closes
SESSION_COOKIE_NAME = 'paulicode_sessionid'  # Custom session cookie name
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access to session cookie
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS
SESSION_COOKIE_SAMESITE = 'Lax'  # CSRF protection

# ============================================
# END CUSTOM AUTHENTICATION
# ============================================


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,  # Minimum 8 characters
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'  # Philippine Time Zone

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "User/static"]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # For production

# Media files (User uploads)
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ============================================
# JAZZMIN ADMIN CUSTOMIZATION
# ============================================

JAZZMIN_SETTINGS = {
    # Site branding
    "site_title": "PauliCode Admin",
    "site_header": "PauliCode Administration",
    "site_brand": "PauliCode",
    "site_logo": None,  # Path to your logo: "images/logo.png"
    "login_logo": None,  # Logo on login page
    "login_logo_dark": None,
    "site_logo_classes": "img-circle",
    "site_icon": None,  # Favicon path
    
    # Welcome message
    "welcome_sign": "Welcome to PauliCode Admin Dashboard",
    "copyright": "PauliCode © 2024 | Developed by Bryan Kim Calipes",
    
    # Search model in navbar
    "search_model": ["User.User", "User.Class", "User.Problem"],
    
    # User menu on top right
    "user_avatar": "user_image",  # Field name from your User model
    
    # Top menu links
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Visit Site", "url": "/", "new_window": True},
        {"name": "Dashboard", "url": "/dashboard/", "new_window": True},
        {"model": "User.User"},
        {"app": "User"},
    ],
    
    # Side menu ordering and icons
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    
    # Custom ordering and icons for models
    "order_with_respect_to": [
        "User",
        "User.user",
        "User.class",
        "User.enrollment", 
        "User.problem",
        "User.problemtestcase",
        "User.submission",
        "User.chathistory",
        "User.problemresource",
    ],
    
    # Custom icons for models (Font Awesome)
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        
        "User.user": "fas fa-user-graduate",
        "User.class": "fas fa-chalkboard-teacher",
        "User.enrollment": "fas fa-user-check",
        "User.problem": "fas fa-code",
        "User.problemtestcase": "fas fa-flask",
        "User.submission": "fas fa-file-code",
        "User.chathistory": "fas fa-comments",
        "User.problemresource": "fas fa-folder-open",
    },
    
    # Icons for default groups and users
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    
    # Related modal (popup windows for foreign keys)
    "related_modal_active": True,
    
    # UI Builder - allows customization through admin interface
    "show_ui_builder": True,
    
    # Custom CSS/JS
    "custom_css": None,
    "custom_js": None,
    
    # Change form options
    "changeform_format": "horizontal_tabs",  # Options: "horizontal_tabs", "vertical_tabs", "collapsible", "carousel"
    "changeform_format_overrides": {
        "User.user": "horizontal_tabs",
        "User.class": "horizontal_tabs",
        "User.problem": "vertical_tabs",
    },
    
    # Language chooser
    "language_chooser": False,
}

JAZZMIN_UI_TWEAKS = {
    # Overall theme
    "theme": "flatly",  # Options: "default", "cerulean", "cosmo", "cyborg", "darkly", "flatly", "journal", "litera", "lumen", "lux", "materia", "minty", "pulse", "sandstone", "simplex", "slate", "solar", "spacelab", "superhero", "united", "yeti"
    "dark_mode_theme": "cyborg",  # Theme for dark mode
    
    # Navbar
    "navbar": "navbar-white navbar-light",  # Options: "navbar-white navbar-light", "navbar-dark navbar-dark"
    "navbar_fixed": False,
    "no_navbar_border": False,
    
    # Sidebar
    "sidebar": "sidebar-dark-primary",  # Options: "sidebar-dark-primary", "sidebar-light-primary", "sidebar-dark-warning", etc.
    "sidebar_fixed": True,
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    
    # Body and text
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-primary",  # Options: "navbar-primary", "navbar-secondary", "navbar-info", "navbar-warning", "navbar-danger", "navbar-success"
    "accent": "accent-primary",  # Options: "accent-primary", "accent-warning", "accent-info", etc.
    
    # Footer
    "footer_small_text": False,
    "footer_fixed": False,
    
    # Layout
    "layout_boxed": False,
    
    # Buttons
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
    
    # Actions
    "actions_sticky_top": True,  # Keep action buttons visible when scrolling
}

JAZZMIN_SETTINGS["show_ui_builder"] = True

# Add custom links to sidebar
JAZZMIN_SETTINGS["usermenu_links"] = [
    {"name": "Support", "url": "https://github.com/your-repo/issues", "new_window": True},
    {"model": "auth.user"}
]

# Custom app and model labels
JAZZMIN_SETTINGS["custom_links"] = {
    "User": [{
        "name": "Generate Report", 
        "url": "/report/",
        "icon": "fas fa-chart-line",
        "permissions": ["User.view_submission"]
    }]
}

# Statistics cards on homepage
JAZZMIN_SETTINGS["show_dashboard_summary"] = True

# ============================================
# SECURITY SETTINGS (for Production)
# ============================================

# Uncomment these when deploying to production with HTTPS:
# SECURE_SSL_REDIRECT = True
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
# SECURE_BROWSER_XSS_FILTER = True
# SECURE_CONTENT_TYPE_NOSNIFF = True
# X_FRAME_OPTIONS = 'DENY'

# CSRF Settings
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to read CSRF token
CSRF_COOKIE_SAMESITE = 'Lax'

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'https://flamboyantly-clammy-roselia.ngrok-free.dev',
]



# ============================================
# LOGGING CONFIGURATION (Optional but Recommended)
# ============================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'debug.log'),
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'User': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}