"""
Django settings for PauliCode project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import pymysql
pymysql.install_as_MySQLdb()
pymysql.version_info = (2, 2, 4, "final", 0)

from pathlib import Path
import os
from User.rate_limit_config import RATE_LIMIT_CACHE_CONFIG_DEV, RATE_LIMIT_CACHE_CONFIG

CACHES = RATE_LIMIT_CACHE_CONFIG_DEV

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*e7y)ze6r)abbf6l=kq6@&np+n_ryrws0q!q-=4$l&(3^gb2h4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '*',
    'paulicode.pythonanywhere.com'
                 ]


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'User',
    'channels',
    'Announcement',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'PauliCode.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'PauliCode.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'djangoPauliCode',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8',
        }
    }
}


# ============================================
# CUSTOM AUTHENTICATION CONFIGURATION
# ============================================
AUTH_USER_MODEL = 'User.User'
# Authentication Backends - Use custom backend for school_id login
AUTHENTICATION_BACKENDS = [
    'User.auth_backend.SchoolIDBackend',  # Primary: Custom school_id authentication
    'User.auth_backend.SessionAuthBackend',  # Secondary: Session-based authentication
    'django.contrib.auth.backends.ModelBackend',  # Fallback: Default Django auth
]

# Login/Logout URLs
LOGIN_URL = 'index'  # Redirect here when @login_required fails
LOGIN_REDIRECT_URL = 'dashboard'  # Default redirect after login (can be overridden in views)
LOGOUT_REDIRECT_URL = 'index'  # Redirect here after logout

# Session Configuration
SESSION_COOKIE_AGE = 86400  # 24 hours (in seconds)
SESSION_SAVE_EVERY_REQUEST = True  # Update session on every request
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Keep session even after browser closes
SESSION_COOKIE_NAME = 'paulicode_sessionid'  # Custom session cookie name
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access to session cookie
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS
SESSION_COOKIE_SAMESITE = 'Lax'  # CSRF protection

# ============================================
# END CUSTOM AUTHENTICATION
# ============================================


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,  # Minimum 8 characters
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'  # Philippine Time Zone

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'  
STATICFILES_DIRS = [
    BASE_DIR / "static",        # Root static folder (for announcement.css, announcement.js),   # User app static folder
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # For production

# Media files (User uploads)
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ============================================
# JAZZMIN ADMIN CUSTOMIZATION - FIXED VERSION
# ============================================

# ============================================
# JAZZMIN ADMIN CUSTOMIZATION - FIXED VERSION WITH SIDEBAR
# ============================================

JAZZMIN_SETTINGS = {
    # ============================================
    # SITE BRANDING
    # ============================================
    "site_title": "PauliCode Admin",
    "site_header": "PauliCode Administration",
    "site_brand": "PauliCode Platform",
    "site_logo": None,
    "site_logo_classes": "img-circle",
    "site_icon": None,
    "welcome_sign": "Welcome to PauliCode Admin Dashboard",
    "copyright": "PauliCode © 2025 - Developed by Bryan Kim Calipes",
    
    # ============================================
    # USER MENU
    # ============================================
    "user_avatar": None,
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],  # ✅ Don't hide anything - let custom_links control visibility
    "hide_models": [],
    
    # ============================================
    # TOP MENU
    # ============================================
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "View Site", "url": "/", "new_window": True},
    ],
    
    # ============================================
    # SIDE MENU - CUSTOM STRUCTURE (THIS IS THE KEY FIX!)
    # ============================================
    "custom_links": {
        "User": [
            {
                "name": "👥 All Users",
                "url": "admin:User_user_changelist",
                "icon": "fas fa-users",
                "permissions": ["User.view_user"]
            },
            {
                "name": "👨‍🎓 Students Only",
                "url": "admin:User_user_changelist?user_type__exact=Student",
                "icon": "fas fa-user-graduate",
                "permissions": ["User.view_user"]
            },
            {
                "name": "👨‍🏫 Teachers Only",
                "url": "admin:User_user_changelist?user_type__exact=Teacher",
                "icon": "fas fa-chalkboard-teacher",
                "permissions": ["User.view_user"]
            },
        ],
        "Classes": [
            {
                "name": "📚 All Classes",
                "url": "admin:User_class_changelist",
                "icon": "fas fa-book",
                "permissions": ["User.view_class"]
            },
            {
                "name": "👥 Enrollments",
                "url": "admin:User_enrollment_changelist",
                "icon": "fas fa-user-plus",
                "permissions": ["User.view_enrollment"]
            },
        ],
        "Problems": [
            {
                "name": "📝 All Problems",
                "url": "admin:User_problem_changelist",
                "icon": "fas fa-tasks",
                "permissions": ["User.view_problem"]
            },
            {
                "name": "🧪 Test Cases",
                "url": "admin:User_problemtestcase_changelist",
                "icon": "fas fa-flask",
                "permissions": ["User.view_problemtestcase"]
            },
            {
                "name": "📄 Submissions",
                "url": "admin:User_submission_changelist",
                "icon": "fas fa-file-code",
                "permissions": ["User.view_submission"]
            },
            {
                "name": "📎 Resources",
                "url": "admin:User_problemresource_changelist",
                "icon": "fas fa-paperclip",
                "permissions": ["User.view_problemresource"]
            },
        ],
        "Announcements": [
            {
                "name": "📢 All Announcements",
                "url": "admin:Announcement_announcement_changelist",
                "icon": "fas fa-bullhorn",
                "permissions": ["Announcement.view_announcement"]
            },
            {
                "name": "📌 Pinned",
                "url": "admin:Announcement_announcement_changelist?is_pinned__exact=1",
                "icon": "fas fa-thumbtack",
                "permissions": ["Announcement.view_announcement"]
            },
            {
                "name": "💬 Comments",
                "url": "admin:Announcement_announcementcomment_changelist",
                "icon": "fas fa-comments",
                "permissions": ["Announcement.view_announcementcomment"]
            },
            {
                "name": "❤️ Reactions",
                "url": "admin:Announcement_announcementreaction_changelist",
                "icon": "fas fa-heart",
                "permissions": ["Announcement.view_announcementreaction"]
            },
            {
                "name": "🚨 Reports",
                "url": "admin:Announcement_announcementreport_changelist",
                "icon": "fas fa-flag",
                "permissions": ["Announcement.view_announcementreport"]
            },
            {
                "name": "📎 Files",
                "url": "admin:Announcement_announcementfile_changelist",
                "icon": "fas fa-file-alt",
                "permissions": ["Announcement.view_announcementfile"]
            },
            {
                "name": "🔗 Links",
                "url": "admin:Announcement_announcementlink_changelist",
                "icon": "fas fa-link",
                "permissions": ["Announcement.view_announcementlink"]
            },
        ],
        "System": [
            {
                "name": "💬 Chat History",
                "url": "admin:User_chathistory_changelist",
                "icon": "fas fa-comment-dots",
                "permissions": ["User.view_chathistory"]
            },
            {
                "name": "✉️ Email Verifications",
                "url": "admin:User_emailverification_changelist",
                "icon": "fas fa-envelope",
                "permissions": ["User.view_emailverification"]
            },
        ],
    },
    
    # ============================================
    # ICONS FOR MODELS (Keep these for detail pages)
    # ============================================
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        
        "User.User": "fas fa-user-graduate",
        "User.Class": "fas fa-chalkboard-teacher",
        "User.Problem": "fas fa-code",
        "User.ProblemTestCase": "fas fa-flask",
        "User.Submission": "fas fa-file-code",
        "User.Enrollment": "fas fa-user-plus",
        "User.ChatHistory": "fas fa-comments",
        "User.ProblemResource": "fas fa-file-pdf",
        "User.EmailVerification": "fas fa-envelope-open-text",
        
        "Announcement": "fas fa-bullhorn",
        "Announcement.Announcement": "fas fa-bullhorn",
        "Announcement.AnnouncementFile": "fas fa-file-alt",
        "Announcement.AnnouncementLink": "fas fa-link",
        "Announcement.AnnouncementReaction": "fas fa-heart",
        "Announcement.AnnouncementComment": "fas fa-comment",
        "Announcement.AnnouncementPin": "fas fa-thumbtack",
        "Announcement.AnnouncementReport": "fas fa-flag",
    },
    
    # ============================================
    # DEFAULT ICON PARENTS
    # ============================================
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    
    # ============================================
    # RELATED MODAL
    # ============================================
    "related_modal_active": True,
    
    # ============================================
    # CUSTOM CSS/JS
    # ============================================
    "custom_css": None,
    "custom_js": None,
    
    # ============================================
    # SHOW UI BUILDER
    # ============================================
    "show_ui_builder": True,
    
    # ============================================
    # CHANGE VIEW LINKS
    # ============================================
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs"
    },
    
    # ============================================
    # LANGUAGE CHOOSER
    # ============================================
    "language_chooser": False,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": True,
    "brand_small_text": False,
    "brand_colour": "navbar-teal",
    "accent": "accent-info",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-olive",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "darkly",
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    "actions_sticky_top": False
}


# ============================================
# SECURITY SETTINGS (for Production)
# ============================================

# Uncomment these when deploying to production with HTTPS:
# SECURE_SSL_REDIRECT = True
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
# SECURE_BROWSER_XSS_FILTER = True
# SECURE_CONTENT_TYPE_NOSNIFF = True
# X_FRAME_OPTIONS = 'DENY'

# CSRF Settings
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to read CSRF token
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'https://paulicode.pythonanywhere.com',
]


# ============================================
# EMAIL CONFIGURATION
# ============================================
# Gmail SMTP Configuration (for sending real emails)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'bryankimcalipes@gmail.com'
EMAIL_HOST_PASSWORD = 'smea gqno felb djtr'
DEFAULT_FROM_EMAIL = 'bryankimcalipes@gmail.com'

# For development file backend (saves emails to file for inspection):
# EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'
# EMAIL_FILE_PATH = os.path.join(BASE_DIR, 'sent_emails')

# For console backend (prints emails to console):
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# ============================================
# LOGGING CONFIGURATION (Optional but Recommended)
# ============================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'debug.log'),
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'User': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}