# Generated by Django 4.2.5 on 2025-12-11 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('upload_icon', models.ImageField(blank=True, null=True, upload_to='class_icons/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('class_type', models.CharField(choices=[('programming', 'Programming'), ('cybersecurity', 'Cybersecurity')], default='programming', help_text='Type of class: Programming or Cybersecurity', max_length=20)),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'db_table': 'class',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('problem_id', models.AutoField(primary_key=True, serialize=False)),
                ('problem_title', models.CharField(max_length=200)),
                ('problem_description', models.TextField()),
                ('problem_type', models.CharField(choices=[('Assignment', 'Assignment'), ('Quiz', 'Quiz')], max_length=20)),
                ('total_score', models.IntegerField(default=100)),
                ('time_limit', models.IntegerField(blank=True, help_text='Time limit in minutes', null=True)),
                ('due_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('challenge_file', models.FileField(blank=True, help_text='Upload challenge files (PDF, ZIP, etc.)', null=True, upload_to='challenge_files/')),
                ('correct_answer', models.TextField(blank=True, help_text='Correct answer for cybersecurity challenges (case-insensitive comparison)', null=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='User.class')),
            ],
            options={
                'verbose_name': 'Problem',
                'verbose_name_plural': 'Problems',
                'db_table': 'problem',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('school_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('user_type', models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student')], max_length=10)),
                ('user_image', models.ImageField(blank=True, default='profile_pic/default.png', null=True, upload_to='profile_pic/')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'user',
                'ordering': ['school_id'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.TextField(blank=True, null=True)),
                ('answer_text', models.TextField(blank=True, help_text='Written answer for cybersecurity challenges', null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Graded', 'Graded'), ('Reviewed', 'Reviewed')], default='Pending', max_length=20)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('problem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='User.problem')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
                'db_table': 'submission',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ProblemTestCase',
            fields=[
                ('test_case_id', models.AutoField(primary_key=True, serialize=False)),
                ('input_data', models.TextField(blank=True, null=True)),
                ('expected_output', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('problem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='User.problem')),
            ],
            options={
                'verbose_name': 'Test Case',
                'verbose_name_plural': 'Test Cases',
                'db_table': 'problem_test_case',
                'ordering': ['test_case_id'],
            },
        ),
        migrations.CreateModel(
            name='ProblemResource',
            fields=[
                ('resource_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title of the resource', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the resource', null=True)),
                ('file', models.FileField(help_text='Upload problem resources (PDF, DOCX, PPTX, images, etc.)', upload_to='problem_resources/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.CharField(blank=True, max_length=20)),
                ('file_extension', models.CharField(blank=True, max_length=10)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='User.problem')),
            ],
            options={
                'verbose_name': 'Problem Resource',
                'verbose_name_plural': 'Problem Resources',
                'db_table': 'problem_resource',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes_taught', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('user', 'User'), ('ai', 'AI')], max_length=10)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat History',
                'verbose_name_plural': 'Chat Histories',
                'db_table': 'chat_history',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('enrolled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='User.class')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'db_table': 'enrollment',
                'ordering': ['-enrolled_at'],
                'unique_together': {('class_id', 'student_id')},
            },
        ),
    ]
