# Generated by Django 4.2.5 on 2025-12-04 02:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('upload_icon', models.ImageField(blank=True, null=True, upload_to='class_icons/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'db_table': 'class',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('problem_id', models.AutoField(primary_key=True, serialize=False)),
                ('problem_title', models.CharField(max_length=200)),
                ('problem_description', models.TextField()),
                ('problem_type', models.CharField(choices=[('Assignment', 'Assignment'), ('Quiz', 'Quiz')], max_length=20)),
                ('total_score', models.IntegerField(default=100)),
                ('time_limit', models.IntegerField(help_text='Time limit in minutes')),
                ('due_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='User.class')),
            ],
            options={
                'verbose_name': 'Problem',
                'verbose_name_plural': 'Problems',
                'db_table': 'problem',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('school_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('user_type', models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student')], max_length=10)),
                ('user_image', models.ImageField(blank=True, default='profile_pic/default.png', null=True, upload_to='profile_pic/')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'user',
                'ordering': ['school_id'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.TextField()),
                ('score', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Graded', 'Graded'), ('Reviewed', 'Reviewed')], default='Pending', max_length=20)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('problem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='User.problem')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='User.user')),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
                'db_table': 'submission',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ProblemTestCase',
            fields=[
                ('test_case_id', models.AutoField(primary_key=True, serialize=False)),
                ('input_data', models.TextField(blank=True, null=True)),
                ('expected_output', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('problem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='User.problem')),
            ],
            options={
                'verbose_name': 'Test Case',
                'verbose_name_plural': 'Test Cases',
                'db_table': 'problem_test_case',
                'ordering': ['test_case_id'],
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems_created', to='User.user'),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes_taught', to='User.user'),
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('user', 'User'), ('ai', 'AI')], max_length=10)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_history', to='User.user')),
            ],
            options={
                'verbose_name': 'Chat History',
                'verbose_name_plural': 'Chat Histories',
                'db_table': 'chat_history',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('enrolled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='User.class')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='User.user')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'db_table': 'enrollment',
                'ordering': ['-enrolled_at'],
                'unique_together': {('class_id', 'student_id')},
            },
        ),
    ]
