# Generated by Django 4.1.13 on 2025-10-25 16:16

import User.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_class_problem_alter_user_user_image_submission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(default='profile_pic/default.png', upload_to=User.models.image_path),
        ),
    ]
