# Generated by Django 4.2.5 on 2025-12-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_type',
            field=models.CharField(choices=[('programming', 'Programming'), ('cybersecurity', 'Cybersecurity')], default='programming', help_text='Type of class: Programming or Cybersecurity', max_length=20),
        ),
    ]
