# Generated by Django 4.2.5 on 2025-12-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_class_class_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='challenge_file',
            field=models.FileField(blank=True, help_text='Upload challenge files (PDF, ZIP, etc.)', null=True, upload_to='challenge_files/'),
        ),
        migrations.AddField(
            model_name='submission',
            name='answer_text',
            field=models.TextField(blank=True, help_text='Written answer for cybersecurity challenges', null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='time_limit',
            field=models.IntegerField(blank=True, help_text='Time limit in minutes', null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
