# Generated by Django 4.1.13 on 2025-10-25 16:22

import User.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_user_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(default='profile_pic/image.png', upload_to=User.models.image_path),
        ),
    ]
