# Generated by Django 4.2.5 on 2025-12-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_problem_challenge_file_submission_answer_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='correct_answer',
            field=models.TextField(blank=True, help_text='Correct answer for cybersecurity challenges (case-insensitive comparison)', null=True),
        ),
    ]
