# Generated by Django 4.1.13 on 2025-11-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_user_user_image'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('problem_id', 'student_id'), name='unique_submission_per_student'),
        ),
    ]
