# Generated by Django 4.2.5 on 2025-12-05 18:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_problem_correct_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemResource',
            fields=[
                ('resource_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(help_text='Upload problem resources (PDF, DOCX, PPTX, images, etc.)', upload_to='problem_resources/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.CharField(blank=True, max_length=20)),
                ('file_extension', models.CharField(blank=True, max_length=10)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='User.problem')),
            ],
            options={
                'verbose_name': 'Problem Resource',
                'verbose_name_plural': 'Problem Resources',
                'db_table': 'problem_resource',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
