# Generated by Django 4.1.13 on 2025-11-03 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_submission_unique_submission_per_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('user', 'User'), ('ai', 'AI')], max_length=10, verbose_name='Message Sender')),
                ('message', models.TextField(verbose_name='Message Content')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Sent At')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_history', to='User.user')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='chathistory',
            index=models.Index(fields=['school_id', 'timestamp'], name='User_chathi_school__aed9a7_idx'),
        ),
    ]
