# Generated by Django 4.1.13 on 2025-11-03 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_chathistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='User.class'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='User.user'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='User.class'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_problems', to='User.user'),
        ),
        migrations.AlterField(
            model_name='problemtestcase',
            name='problem_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='User.problem'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='problem_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='User.problem'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='User.user'),
        ),
    ]
