# Generated by Django 4.2.5 on 2025-12-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_problemresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemresource',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the resource', null=True),
        ),
        migrations.AddField(
            model_name='problemresource',
            name='title',
            field=models.CharField(default='Untitled Resource', help_text='Title of the resource', max_length=200),
            preserve_default=False,
        ),
    ]
