# Generated by Django 4.1.13 on 2025-11-03 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_alter_enrollment_class_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.class'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.class'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user'),
        ),
        migrations.AlterField(
            model_name='problemtestcase',
            name='problem_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.problem'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='problem_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.problem'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user'),
        ),
    ]
