# Generated by Django 4.2.16 on 2026-04-08 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Announcement', '0001_initial'),
        ('User', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcementreaction',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='Announcement.announcement'),
        ),
        migrations.AddField(
            model_name='announcementreaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcementpin',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='Announcement.announcement'),
        ),
        migrations.AddField(
            model_name='announcementpin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcementlink',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='Announcement.announcement'),
        ),
        migrations.AddField(
            model_name='announcementfile',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='Announcement.announcement'),
        ),
        migrations.AddField(
            model_name='announcementcomment',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Announcement.announcement'),
        ),
        migrations.AddField(
            model_name='announcementcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='User.class'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='announcementreport',
            unique_together={('announcement', 'reporter')},
        ),
        migrations.AlterUniqueTogether(
            name='announcementreaction',
            unique_together={('announcement', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='announcementpin',
            unique_together={('announcement', 'user')},
        ),
    ]
