# Generated by Django 4.2.5 on 2025-12-18 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Announcement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('dismissed', 'Dismissed'), ('action_taken', 'Action Taken')], default='pending', max_length=20)),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='Announcement.announcement')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'announcement_report',
                'ordering': ['-reported_at'],
                'unique_together': {('announcement', 'reporter')},
            },
        ),
    ]
