# Generated by Django 4.2.5 on 2025-12-18 15:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Announcement', '0002_announcementreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='file',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='link',
        ),
        migrations.CreateModel(
            name='AnnouncementLink',
            fields=[
                ('link_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=500)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='Announcement.announcement')),
            ],
            options={
                'ordering': ['added_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementFile',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='announcements/files/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='Announcement.announcement')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
